//shouldn't be committed to version control if the repo is public.

package com.humazed.foursquarenearby

//const val CLIENT_ID = "OYOAJQXZDNYHPTYPDDXN3GH4CC4Z35PLWESXDEUCJIZVWCON"
//const val CLIENT_SECRET = "TAQJQZAJPSSG2DLBTZMBZRNHKJFKWRR0JGYAGWRBQA20GM4E"

const val CLIENT_ID = "4WPZKS1GJD4OZ5PNN0ETQG5GD5VXVQVGRYDY5WYTDS0DC1KI"
const val CLIENT_SECRET = "KIFTF43NSJSTTGVHAHWRFCEJMVFWMJCUFR45P3HQ5INP2IGS"

//const val CLIENT_ID = "1WIOHZJRQRYOYUJMSTR0BX0CGSE3QNIN4D40W35UJ13BUV0E"
//const val CLIENT_SECRET = "QE23CUWS3BY3IZJM4OTC0LPJZEQ3IPQJC0YNSRHYRKYJ2HJB"


const val SIZE = "150x150"


const val KEY_LATITUDE = "KEY_LATITUDE"
const val KEY_LONGITUDE = "KEY_LONGITUDE"

const val KEY_LIVE_LOCATION = "KEY_LIVE_LOCATION"
