//shouldn't be committed to version control if the repo is public.

package com.humazed.foursquarenearby.api

const val CLIENT_ID = "OYOAJQXZDNYHPTYPDDXN3GH4CC4Z35PLWESXDEUCJIZVWCON"
const val CLIENT_SECRET = "TAQJQZAJPSSG2DLBTZMBZRNHKJFKWRR0JGYAGWRBQA20GM4E"


//const val CLIENT_ID = "1WIOHZJRQRYOYUJMSTR0BX0CGSE3QNIN4D40W35UJ13BUV0E"
//const val CLIENT_SECRET = "QE23CUWS3BY3IZJM4OTC0LPJZEQ3IPQJC0YNSRHYRKYJ2HJB"


const val SIZE = "150x150"
